markdown: kramdown
highlighter: true
permalink: /:categories/:title
timezone: America/Seattle
baseurl: "http://amritamaz.me"

name: Amrita Mazumdar
author: Amrita Mazumdar
twitter: '@amritamaz'
description: Thoughts and musings by amrita mazumdar
url: http://www.amritamaz.me/blog
