markdown: kramdown
highlighter: pygments
permalink: /:categories/:title
timezone: America/Seattle
categories: [art,tech,notes,writing,visual,technical,design,sewing,lifestyle]
# baseurl: "http://amritamaz.net/"

name: Amrita Mazumdar
author: Amrita Mazumdar
title: 'Amrita Mazumdar'
email: amritamaz@gmail.com
twitter: '@amritamaz'
description: 'Amrita Mazumdar, computer science PhD student and creative person.'